oauth-wg/draft-ietf-oauth-status-list

- LICENSE.md
- README.md
- draft-looker-jwt-cwt-status-list.md
Fixing links to point to new org
> fix broken links

- draft-looker-jwt-cwt-status-list.md
gathering some ideas on privacy and security considerations
> Drafting Privacy and Security Considerations

- draft-looker-jwt-cwt-status-list.md
> some spelling fixes

- draft-looker-jwt-cwt-status-list.md
- src/status_jwt.py
- src/status_list.py
- src/test.py
- src/util.py
- fixes the examples to use constant timestamps in gzip encoding
- minor changes/fixes to the ascii art / code blocks
> fix examples

- draft-looker-oauth-jwt-cwt-status-list.md
Closes #35
Simple fix to example
> fix reference token example

- draft-looker-oauth-jwt-cwt-status-list.md
Closes #19 
reorder section on Referenced Token and Status List Token
> reorder sections on Referenced Token and Status List Token

- draft-looker-oauth-jwt-cwt-status-list.md
> add as author

- draft-looker-oauth-jwt-cwt-status-list.md
Closes #64 
Use term Relying Party and Issuer
> rename Verifier to Relying Part and add some terminology

- draft-ietf-oauth-status-list.md
Closes #78 
Change typo in Status List Token sub claim description
> Change typo in Status List Token sub claim description

- draft-ietf-oauth-status-list.md
> Rename  Draft Title

- draft-ietf-oauth-status-list.md
Closes #54 
This PR adds a section on design considerations.
> design considerations

- draft-ietf-oauth-status-list.md
> Add placeholder for cbor-based referenced tokens

- .github/CODEOWNERS
- draft-ietf-oauth-status-list.md
Some spelling fixes
Add IANA registry to history
add myself to codeowners
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/c2bo/minor-edits/draft-ietf-oauth-status-list.html)
> Editorial changes + fix codeowners

- draft-ietf-oauth-status-list.md
Closes # 
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/paulbastian/sd-jwt-ref#go.draft-ietf-oauth-status-list.html)
> add SD-JWT VC as reference to the Issuer-Holder-Verifier model

- draft-ietf-oauth-status-list.md
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/c2bo/fix-references/draft-ietf-oauth-status-list.html)
> fix broken references

- draft-ietf-oauth-status-list.md
Closes #96 
Alternative to #49 as it had gone stale.
> add initial ttl language

- src/requirements.txt
> upgrade python dependencies

- .github/workflows/publish.yml
add cborg dependency to publish workflow
> add cborg dependency to publish workflow

- LICENSE.md
- README.md
- draft-ietf-oauth-status-list.md
> fix references after moving the repo to the new org

- .github/workflows/archive.yml
- .github/workflows/ghpages.yml
- .github/workflows/publish.yml
- .github/workflows/update.yml
Updates to current versions from https://github.com/martinthomson/internet-draft-template/
> Update github action versions

- draft-ietf-oauth-status-list.md
closes #144
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/cwt-typ/draft-ietf-oauth-status-list.html
> Update CWT type reference (published RFC)

- draft-ietf-oauth-status-list.md
> Change affiliation

- draft-ietf-oauth-status-list.md
> relax requirements for status_list claims to contain other parameters

- draft-ietf-oauth-status-list.md
Closes #134 
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/validation-rules/draft-ietf-oauth-status-list.html
> first attempt on validation rules

- .gitignore
- README.md
> add testing tool

- draft-ietf-oauth-status-list.md
Closes #58
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/cors/draft-ietf-oauth-status-list.html
> add cors considerations to the http endpoint

- draft-ietf-oauth-status-list.md
Closes #146 
Closes #165 
Closes #132 
Closes #93 
Closes #73
> update security consideration

- draft-ietf-oauth-status-list.md
> remove constraint that Status List Token must not use a MAC

- draft-ietf-oauth-status-list.md
> improve section on Status Types and introduce IANA registry for it

- draft-ietf-oauth-status-list.md
> fix: update cwt claim definitions

- README.md
> Add implementations to README

- draft-ietf-oauth-status-list.md
Closes #188
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/status-code-redirect/draft-ietf-oauth-status-list.html
> status codes & redirect

- draft-ietf-oauth-status-list.md
> Resolution for issue 182

- draft-ietf-oauth-status-list.md
> Add further guidance around ttl

- draft-ietf-oauth-status-list.md
> update security considerations

- draft-ietf-oauth-status-list.md
Closes #194 
We would register:
CWT Status Mechanisms registry in CWT 
JWT Status Mechanisms registry in JWT 
Status Types registry in OAuth parameters
Any ideas how we could simplify this?
> additional text for iana registry

- draft-ietf-oauth-status-list.md
> changes as requested by IANA review

- .gitignore
- draft-ietf-oauth-status-list.md
Close #83 
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/83-prior-art/draft-ietf-oauth-status-list.html
> Mention prior art

- draft-ietf-oauth-status-list.md
> Minor editorial change to address issue 217

- draft-ietf-oauth-status-list.md
Trying to fix some obvious spelling mistakes and increase readability in general. Not sure about all of the minor / non-obvious changes.
> editorial fixes

- draft-ietf-oauth-status-list.md
> editorial changes on terminology and Referenced Tokens

- draft-ietf-oauth-status-list.md
> Fix issue 225

- draft-ietf-oauth-status-list.md
> security consideration for signature/mac

- draft-ietf-oauth-status-list.md
> aggregation uri text

- draft-ietf-oauth-status-list.md
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/fix-intended-status/draft-ietf-oauth-status-list.html
> fix category

- draft-ietf-oauth-status-list.md
> fix referenced token terminology

- draft-ietf-oauth-status-list.md
> Holders may also fetch and verify Status List Tokens

- draft-ietf-oauth-status-list.md
> Clarify Status List definition

- draft-ietf-oauth-status-list.md
> Change Controller IESG for OAuths Parameters Registration

- draft-ietf-oauth-status-list.md
> add coap content format registration

- README.md
Updating the README with links to
- BDR Implementation
- Adorsys Implementation
> Add more open source implementations to the Readme

- draft-ietf-oauth-status-list.md
Finally got approval from the company
> Update Paul's affiliation

- draft-ietf-oauth-status-list.md
> some nitpicks and clarifications
