draft-looker-oauth-jwt-cwt-status-list.md
Closes #59 
IANA Consideration to register JWT Claim names and media types
=> initial IANA section for media types and jwt claim names

draft-ietf-oauth-status-list.md, src/main.py, src/status_list.py, src/status_token.py
Closes #67 and #39.
Switches to zlib instead of gzip encoding and adds the recommendation to use the best available compression.
=> switch to deflate + zlib instead of gzip

draft-ietf-oauth-status-list.md
This feedback comes from applying the Status List to an implementation of a general OAuth 2.x server issuing JWT Access Tokens.
Such implementation will typically not keep record of any issued JWT Access Tokens (their claims, expiry, etc) until they need to be revoked due any reason, e.g. getting leaked or just being explicitly revoked by the client.
In such cases the issuer considers the token as VALID when issuing the Status List but this state will not necessarily reflect the token's validity as per the JWT validation rules for claims like nbf or exp. This is important to point out so that the status list is not mistaken for an alternative to actually validating the referenced token's claim set.
=> VALID does not precede J/CWT processing rules

draft-ietf-oauth-status-list.md
fixes the rendering of the last history (01)
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/c2bo/history-rendering/draft-ietf-oauth-status-list.html)
=> added newline to fix rendering for history

draft-ietf-oauth-status-list.md
Establish a mechanism that allows for other revocation means in the Referenced Token as discussed in #85. The only thing i changed was to call the reference "status_list" but I am open to change it to "status_bitstring" if we think that is a better fit.
Closes #85 
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/c2bo/status-reference/draft-ietf-oauth-status-list.html)
=> Establish a mechanism that allows for other revocation means in the Referenced Token

draft-ietf-oauth-status-list.md
=> clarifying deflate/zlib

draft-ietf-oauth-status-list.md
Fixes most of #92 
- Relaxes requirements on referenced token in terminology
- issuer in status list token is only required when also present in referenced token (and matching checked)
- reorder references
[click here for rendered preview of PR](https://vcstuff.github.io/draft-ietf-oauth-status-list/c2bo/relax-referenced-token/draft-ietf-oauth-status-list.html)
=> relax requirements referenced token

draft-ietf-oauth-status-list.md
=> improve privacy consideration to recommend re-issuance

draft-ietf-oauth-status-list.md
removes the http caching reference as we introduced the `ttl` option.
closes #135
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/http-caching/draft-ietf-oauth-status-list.html
=> remove http caching section

draft-ietf-oauth-status-list.md, src/main.py, src/referenced_token.py, src/status_list.py, src/status_token.py
Changes the CWT example to a Hex and annotated Hex version instead of diagnstic.
closes: #113
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/cwt-referencedtoken/draft-ietf-oauth-status-list.html
Did you have time to check this example with your team @tplooker?
=> Referenced Token CWT example

draft-ietf-oauth-status-list.md
Adds a claim key for `status_list` used in the status list token in CWT format and fixes the reference.
=> add cwt claim key for status_list 

draft-ietf-oauth-status-list.md
- fixes the list rendering (missing newline)
- clarifies IANA text to just reference other tokens
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/editiorial-fixes/draft-ietf-oauth-status-list.html
=> fix rendering & improve IANA registration text

draft-ietf-oauth-status-list.md, src/main.py, src/status_list.py
`status_list` in the Status List Token in CWT form was encoded as Byte String instead of Map (type 5) as defined in the CBOR Section (4.2).
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/fix-cwt-statuslist-encoding/draft-ietf-oauth-status-list.html
=> fix CWT status_list map encoding

src/status_token.py
#160 introduced the new claim key for status_list within the status list cwt, but the example wasn't adjusted
=> status list token cwt example uses new claim key

draft-ietf-oauth-status-list.md
closes #38
closes #168
closes #137
Rendered preview: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/mixing-formats/draft-ietf-oauth-status-list.html
This PR attempts to add a bit of language about mixing formats and also changes the content-type in the status list response to SHOULD and language around content type parsing that is similar to the language used in HTTP/1.1.
I am happy to remove the media types part if we want a bit more discussion, but when I started writing this, it felt like right path so I decided to include it as a proposal.
=> mixing formats and media types

draft-ietf-oauth-status-list.md
=> differentiate unlinkability between Issuer-RP and RP-RP

.github/workflows/ghpages.yml, .github/workflows/publish.yml, src/requirements.txt
Github updated the ubuntu version of the runners creating problems with oscrypto - this should fix the builds for now.
=> chore: fix python example build for newer ubuntu versions

draft-ietf-oauth-status-list.md
Minor change to address the use of the homonym "write" instead of "right".
=> Nit - change "write" to "right" for describing directionality

draft-ietf-oauth-status-list.md, src/main.py, src/referenced_token.py, src/status_list.py, src/util.py
Fixes #216 
I've moved the existing 2 bit examples and ascii art up - we can revert that change, but it felt more consistent to me that way
I am not exactly sure how to better displays the input (status values for specific positions) - any ideas?
Rendered version: https://drafts.oauth.net/draft-ietf-oauth-status-list/216-test-vectors/draft-ietf-oauth-status-list.html
=> More test vectors

draft-ietf-oauth-status-list.md
Closes #237 
Closes #235
Closes #234 
Closes #227 
Closes #224
=> add recommendations for Key Resolution and Trust Management

draft-ietf-oauth-status-list.md
=> mention key resolution in the validation rules section

draft-ietf-oauth-status-list.md
=> Holders may also fetch and verify Status List Tokens

draft-ietf-oauth-status-list.md, src/status_token.py
Closes #262 
COSE/CWT typ behaves a bit differently than JOSE/JWT typ and requires the full media type.
=> fix cwt typ to use full media type

draft-ietf-oauth-status-list.md
Closes #267 
I only added the CDDL for the StatusList object CBOR encoding which seemed to be the most important to provide CDDL for. I don't think CDDL for the CWT would help (and I didn't find many examples in other specs doing CDDL for CWT).
@rohanmahy Would that work for you?
=> Add cddl for statuslist cbor encoding

.github/workflows/ghpages.yml, .github/workflows/publish.yml, draft-ietf-oauth-status-list.md, src/bench.py, src/requirements.txt, src/status_list.py
Closes #276 
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/276-size-comparison/draft-ietf-oauth-status-list.html#name-size-comparison
Not really happy with  how the table renders, but there seem to be some limit to what is possible with kramdown table parsing?
=> size comparison

draft-ietf-oauth-status-list.md
=> some nitpicks

draft-ietf-oauth-status-list.md
Rendered Version: https://drafts.oauth.net/draft-ietf-oauth-status-list/c2bo/feedback-from-rifaat/draft-ietf-oauth-status-list.html
=> Incorporate feedback from Rifaat

draft-ietf-oauth-status-list.md
=> fix: issue 298

draft-ietf-oauth-status-list.md
Closes #302 
Wording feels somewhat rough, but I think this is the best place to add that note. Any ideas to improve wording?
=> add note on CWT encoding
